name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_timezone: ^5.0.1
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  timezone: ^0.10.0
  workmanager:
   git:
     url: https://github.com/fluttercommunity/flutter_workmanager.git
     path: workmanager
     ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 700
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/Poppins-Thin.ttf
         weight: 100
